"""DuckDB analytical layer over the canonical Parquet dataset (Step 3A)."""

from dota_predictor.features.availability import (
    FeatureAvailabilityError,
    SnapshotStage,
    assert_columns_allowed_for_stage,
    columns_allowed_for_stage,
)
from dota_predictor.features.config import (
    FeatureStoreConfig,
    ReferenceStoreConfig,
    load_feature_store_config,
    load_reference_store_config,
)
from dota_predictor.features.duckdb_layer import (
    DRAFT_EVENTS_VIEW,
    GAME_VERSIONS_VIEW,
    HEROES_VIEW,
    MATCH_PLAYERS_VIEW,
    MATCHES_VIEW,
    FeatureDuckDBConnection,
    connect,
    register_reference_views,
)
from dota_predictor.features.hero_meta import (
    HERO_META_COLUMNS,
    HERO_META_IDENTITY_COLUMNS,
    HERO_META_METRIC_COLUMNS,
    RECENT_WINDOW_DAYS,
    HeroMetaState,
    build_hero_meta,
    hero_meta_sql,
    rank_hero_meta,
)
from dota_predictor.features.pre_draft_snapshot import (
    FEATURE_COLUMNS,
    IDENTITY_COLUMNS,
    PLAYER_HISTORY_FEATURE_COLUMNS,
    PRE_DRAFT_SNAPSHOT_SQL,
    ROSTER_CONTINUITY_FEATURE_COLUMNS,
    SNAPSHOT_COLUMNS,
    TARGET_COLUMN,
    TEAM_HISTORY_FEATURE_COLUMNS,
    PreDraftSnapshot,
    build_pre_draft_snapshot,
)
from dota_predictor.features.team_elo import (
    DEFAULT_ELO_CONFIG,
    DIRE_TEAM_ELO_COLUMN,
    RADIANT_TEAM_ELO_COLUMN,
    TEAM_ELO_DELTA_COLUMN,
    TEAM_ELO_FEATURE_COLUMNS,
    EloConfig,
    InvalidTeamIdError,
    compute_team_elo_features,
    expected_score,
)
from dota_predictor.features.temporal import (
    HISTORICAL_START_TIME_SQL_CONDITION,
    is_historical,
)

__all__ = [
    "DEFAULT_ELO_CONFIG",
    "DIRE_TEAM_ELO_COLUMN",
    "DRAFT_EVENTS_VIEW",
    "FEATURE_COLUMNS",
    "GAME_VERSIONS_VIEW",
    "HEROES_VIEW",
    "HERO_META_COLUMNS",
    "HERO_META_IDENTITY_COLUMNS",
    "HERO_META_METRIC_COLUMNS",
    "HISTORICAL_START_TIME_SQL_CONDITION",
    "IDENTITY_COLUMNS",
    "MATCHES_VIEW",
    "MATCH_PLAYERS_VIEW",
    "PLAYER_HISTORY_FEATURE_COLUMNS",
    "PRE_DRAFT_SNAPSHOT_SQL",
    "RADIANT_TEAM_ELO_COLUMN",
    "RECENT_WINDOW_DAYS",
    "ROSTER_CONTINUITY_FEATURE_COLUMNS",
    "SNAPSHOT_COLUMNS",
    "TARGET_COLUMN",
    "TEAM_ELO_DELTA_COLUMN",
    "TEAM_ELO_FEATURE_COLUMNS",
    "TEAM_HISTORY_FEATURE_COLUMNS",
    "EloConfig",
    "FeatureAvailabilityError",
    "FeatureDuckDBConnection",
    "FeatureStoreConfig",
    "HeroMetaState",
    "InvalidTeamIdError",
    "PreDraftSnapshot",
    "ReferenceStoreConfig",
    "SnapshotStage",
    "assert_columns_allowed_for_stage",
    "build_hero_meta",
    "build_pre_draft_snapshot",
    "columns_allowed_for_stage",
    "compute_team_elo_features",
    "connect",
    "expected_score",
    "hero_meta_sql",
    "is_historical",
    "load_feature_store_config",
    "load_reference_store_config",
    "rank_hero_meta",
    "register_reference_views",
]
