"""Step 4A: model-ready training dataset assembly and chronological
train/validation/test splitting, built on top of
`features.pre_draft_snapshot`.

Deliberately separate from `features/`: that package describes what
was knowable at prediction time; this package describes which of its
already-computed rows/columns are usable for ML and how they are
split. No feature/Elo/history computation lives here.
"""

from dota_predictor.training.baselines import (
    ConstantProbabilityBaseline,
    EloOnlyProbabilityBaseline,
    EmpiricalRateBaseline,
)
from dota_predictor.training.dataset import (
    ModelReadyDataset,
    TrainingDatasetError,
    build_model_ready_dataset,
)
from dota_predictor.training.diagnostics import (
    missing_value_report,
    rows_with_any_missing,
)
from dota_predictor.training.evaluation import BenchmarkReport, run_step4b_benchmark
from dota_predictor.training.feature_sets import (
    ALL_FEATURE_COLUMNS,
    DRAFT_COMPARISON_FEATURE_COLUMNS,
    ELO_ONLY_FEATURE_COLUMNS,
    ELO_PLUS_ALL_THREE_COLUMNS,
    ELO_PLUS_DRAFT_COMPARISON_COLUMNS,
    ELO_PLUS_HERO_META_COLUMNS,
    ELO_PLUS_PLAYER_AND_TEAM_HERO_COLUMNS,
    ELO_PLUS_PLAYER_HERO_COLUMNS,
    ELO_PLUS_TEAM_HERO_COLUMNS,
    HERO_META_COMPARISON_COLUMNS,
    HISTORICAL_WITHOUT_ELO_COLUMNS,
    PLAYER_HERO_COMPARISON_COLUMNS,
    POST_DRAFT_BLOCK_ABLATION_SPECS,
    SLICE7_CAREER_SPEC_NAME,
    SLICE7_META_PLAYER_HERO_SPECS,
    TEAM_HERO_COMPARISON_COLUMNS,
    BlockAblationSpec,
)
from dota_predictor.training.logistic_model import (
    LogisticRegressionConfig,
    LogisticRegressionPredictor,
    build_logistic_pipeline,
    standardized_coefficients,
)
from dota_predictor.training.memory_policy import (
    MEMORY_POLICIES,
    POLICY_CURRENT_PLUS_PREVIOUS_VERSION,
    POLICY_EXPANDING,
    POLICY_LAST_180D,
    POLICY_LAST_365D,
    MemoryRestrictedFold,
    restrict_fold_to_memory,
)
from dota_predictor.training.metrics import EvaluationMetrics, evaluate_probabilities
from dota_predictor.training.patch_maturity_diagnostics import (
    DRAFT_BLOCK_SPEC_NAMES,
    PatchMaturityDiagnosticReport,
    attach_patch_maturity,
    build_familiarity_mix,
    run_patch_maturity_diagnostics,
)
from dota_predictor.training.post_draft import (
    PostDraftBenchmarkReport,
    PostDraftBlockAblationReport,
    build_post_draft_model_ready_dataset,
    run_post_draft_benchmark,
    run_post_draft_block_ablation,
)
from dota_predictor.training.preprocessing import (
    PreprocessingSpec,
    build_preprocessing_pipeline,
)
from dota_predictor.training.slice7_meta_player_hero import (
    CAREER_SAMPLE_BUCKET_ORDER,
    COMPATIBILITY_BUCKET_ORDER,
    CONTEST_SHIFT_ABS_DELTA,
    LOW_N_VERSION_THRESHOLD,
    MIN_EXPLICIT_FOR_ROLE_SHIFT,
    PATCH_MATURITY_BIN_ORDER,
    SLICE7_COMBINED_SPEC_NAME,
    SLICE7_RECENT20_SPEC_NAME,
    SLICE7_RECENT20_VOLUME_SPEC_NAME,
    SLICE7_ROLE_SPEC_NAME,
    SLICE7_SAME_VERSION_SPEC_NAME,
    SLICE7_SAME_VERSION_VOLUME_SPEC_NAME,
    Slice7Assembly,
    Slice7BenchmarkReport,
    assign_career_sample_bucket,
    assign_compatibility_bucket,
    assign_patch_maturity_bin,
    build_slice7_model_ready_dataset,
    describe_hero_shift_groups,
    run_slice7_meta_player_hero_benchmark,
)
from dota_predictor.training.split import (
    DEFAULT_SPLIT_CONFIG,
    ChronologicalSplit,
    ChronologicalSplitConfig,
    ChronologicalSplitError,
    DatasetPartition,
    SplitBoundaries,
    chronological_split,
    resolve_split_boundaries,
)
from dota_predictor.training.walk_forward import (
    DEFAULT_WALK_FORWARD_CONFIG,
    ELO_BLOCK_SPEC_NAME,
    WalkForwardConfig,
    WalkForwardFold,
    WalkForwardReport,
    resolve_walk_forward_folds,
    run_post_draft_walk_forward,
)
from dota_predictor.training.walk_forward_memory import (
    WalkForwardMemoryReport,
    run_walk_forward_memory_diagnostics,
)

__all__ = [
    "ALL_FEATURE_COLUMNS",
    "CAREER_SAMPLE_BUCKET_ORDER",
    "COMPATIBILITY_BUCKET_ORDER",
    "CONTEST_SHIFT_ABS_DELTA",
    "DEFAULT_SPLIT_CONFIG",
    "DEFAULT_WALK_FORWARD_CONFIG",
    "DRAFT_BLOCK_SPEC_NAMES",
    "DRAFT_COMPARISON_FEATURE_COLUMNS",
    "ELO_BLOCK_SPEC_NAME",
    "ELO_ONLY_FEATURE_COLUMNS",
    "ELO_PLUS_ALL_THREE_COLUMNS",
    "ELO_PLUS_DRAFT_COMPARISON_COLUMNS",
    "ELO_PLUS_HERO_META_COLUMNS",
    "ELO_PLUS_PLAYER_AND_TEAM_HERO_COLUMNS",
    "ELO_PLUS_PLAYER_HERO_COLUMNS",
    "ELO_PLUS_TEAM_HERO_COLUMNS",
    "HERO_META_COMPARISON_COLUMNS",
    "HISTORICAL_WITHOUT_ELO_COLUMNS",
    "LOW_N_VERSION_THRESHOLD",
    "MEMORY_POLICIES",
    "MIN_EXPLICIT_FOR_ROLE_SHIFT",
    "PATCH_MATURITY_BIN_ORDER",
    "PLAYER_HERO_COMPARISON_COLUMNS",
    "POLICY_CURRENT_PLUS_PREVIOUS_VERSION",
    "POLICY_EXPANDING",
    "POLICY_LAST_180D",
    "POLICY_LAST_365D",
    "POST_DRAFT_BLOCK_ABLATION_SPECS",
    "SLICE7_CAREER_SPEC_NAME",
    "SLICE7_COMBINED_SPEC_NAME",
    "SLICE7_META_PLAYER_HERO_SPECS",
    "SLICE7_RECENT20_SPEC_NAME",
    "SLICE7_RECENT20_VOLUME_SPEC_NAME",
    "SLICE7_ROLE_SPEC_NAME",
    "SLICE7_SAME_VERSION_SPEC_NAME",
    "SLICE7_SAME_VERSION_VOLUME_SPEC_NAME",
    "TEAM_HERO_COMPARISON_COLUMNS",
    "BenchmarkReport",
    "BlockAblationSpec",
    "ChronologicalSplit",
    "ChronologicalSplitConfig",
    "ChronologicalSplitError",
    "ConstantProbabilityBaseline",
    "DatasetPartition",
    "EloOnlyProbabilityBaseline",
    "EmpiricalRateBaseline",
    "EvaluationMetrics",
    "LogisticRegressionConfig",
    "LogisticRegressionPredictor",
    "MemoryRestrictedFold",
    "ModelReadyDataset",
    "PatchMaturityDiagnosticReport",
    "PostDraftBenchmarkReport",
    "PostDraftBlockAblationReport",
    "PreprocessingSpec",
    "Slice7Assembly",
    "Slice7BenchmarkReport",
    "SplitBoundaries",
    "TrainingDatasetError",
    "WalkForwardConfig",
    "WalkForwardFold",
    "WalkForwardMemoryReport",
    "WalkForwardReport",
    "assign_career_sample_bucket",
    "assign_compatibility_bucket",
    "assign_patch_maturity_bin",
    "attach_patch_maturity",
    "build_familiarity_mix",
    "build_logistic_pipeline",
    "build_model_ready_dataset",
    "build_post_draft_model_ready_dataset",
    "build_preprocessing_pipeline",
    "build_slice7_model_ready_dataset",
    "chronological_split",
    "describe_hero_shift_groups",
    "evaluate_probabilities",
    "missing_value_report",
    "resolve_split_boundaries",
    "resolve_walk_forward_folds",
    "restrict_fold_to_memory",
    "rows_with_any_missing",
    "run_patch_maturity_diagnostics",
    "run_post_draft_benchmark",
    "run_post_draft_block_ablation",
    "run_post_draft_walk_forward",
    "run_slice7_meta_player_hero_benchmark",
    "run_step4b_benchmark",
    "run_walk_forward_memory_diagnostics",
    "standardized_coefficients",
]
