"""Step 4A: model-ready training dataset assembly and chronological
train/validation/test splitting, built on top of
`features.pre_draft_snapshot`.

Deliberately separate from `features/`: that package describes what
was knowable at prediction time; this package describes which of its
already-computed rows/columns are usable for ML and how they are
split. No feature/Elo/history computation lives here.
"""

from dota_predictor.training.baselines import (
    ConstantProbabilityBaseline,
    EloOnlyProbabilityBaseline,
    EmpiricalRateBaseline,
)
from dota_predictor.training.combat_performance_target import (
    COMBAT_CANDIDATE_COLUMN_NAMES,
    COMBAT_CANDIDATE_SPECS,
    FROZEN_COMBAT_CANDIDATE,
    Slice17DiagnosticReport,
    attach_combat_candidates,
    classify_slice17,
    run_combat_performance_target_diagnostics,
    slice17_report_to_jsonable,
)
from dota_predictor.training.dataset import (
    ModelReadyDataset,
    TrainingDatasetError,
    build_model_ready_dataset,
)
from dota_predictor.training.diagnostics import (
    missing_value_report,
    rows_with_any_missing,
)
from dota_predictor.training.evaluation import BenchmarkReport, run_step4b_benchmark
from dota_predictor.training.farming_performance_target import (
    FARMING_CANDIDATE_COLUMN_NAMES,
    FARMING_CANDIDATE_SPECS,
    Slice13DiagnosticReport,
    attach_farming_candidates,
    run_farming_performance_target_diagnostics,
    slice13_report_to_jsonable,
)
from dota_predictor.training.feature_sets import (
    ALL_FEATURE_COLUMNS,
    DRAFT_COMPARISON_FEATURE_COLUMNS,
    ELO_ONLY_FEATURE_COLUMNS,
    ELO_PLUS_ALL_THREE_COLUMNS,
    ELO_PLUS_DRAFT_COMPARISON_COLUMNS,
    ELO_PLUS_HERO_META_COLUMNS,
    ELO_PLUS_PLAYER_AND_TEAM_HERO_COLUMNS,
    ELO_PLUS_PLAYER_COMBAT_COLUMNS,
    ELO_PLUS_PLAYER_FARMING_COLUMNS,
    ELO_PLUS_PLAYER_HERO_COLUMNS,
    ELO_PLUS_TEAM_HERO_COLUMNS,
    HERO_META_COMPARISON_COLUMNS,
    HISTORICAL_WITHOUT_ELO_COLUMNS,
    PLAYER_COMBAT_COMPARISON_COLUMNS,
    PLAYER_COMBAT_FEATURE_COLUMNS,
    PLAYER_FARMING_COMPARISON_COLUMNS,
    PLAYER_FARMING_FEATURE_COLUMNS,
    PLAYER_HERO_COMPARISON_COLUMNS,
    POST_DRAFT_BLOCK_ABLATION_SPECS,
    SLICE7_CAREER_SPEC_NAME,
    SLICE7_META_PLAYER_HERO_SPECS,
    SLICE8_CAREER_SPEC_NAME,
    SLICE8_GATE_SPEC_NAME,
    SLICE8_INTERACTION_COLUMNS,
    SLICE8_META_PLAYER_HERO_SPECS,
    SLICE8_STATIC_SPECS,
    SLICE9_CANDIDATE_SPEC,
    SLICE9_CANDIDATE_SPEC_NAME,
    SLICE9_FROZEN_SPECS,
    SLICE9_REFERENCE_SPEC,
    SLICE9_REFERENCE_SPEC_NAME,
    SLICE15_CANDIDATE_SPEC,
    SLICE15_CANDIDATE_SPEC_NAME,
    SLICE15_FROZEN_SPECS,
    SLICE15_REFERENCE_SPEC,
    SLICE15_REFERENCE_SPEC_NAME,
    SLICE19_CANDIDATE_SPEC,
    SLICE19_CANDIDATE_SPEC_NAME,
    SLICE19_FROZEN_SPECS,
    SLICE19_REFERENCE_SPEC,
    SLICE19_REFERENCE_SPEC_NAME,
    TEAM_HERO_COMPARISON_COLUMNS,
    BlockAblationSpec,
    slice8_interaction_column,
)
from dota_predictor.training.hero_performance_profile import (
    CLASSIFICATION_A as SLICE21_CLASSIFICATION_A,
)
from dota_predictor.training.hero_performance_profile import (
    CLASSIFICATION_B as SLICE21_CLASSIFICATION_B,
)
from dota_predictor.training.hero_performance_profile import (
    CLASSIFICATION_C as SLICE21_CLASSIFICATION_C,
)
from dota_predictor.training.hero_performance_profile import (
    HERO_COMBAT_PROFILE_KEY,
    HERO_COMBAT_PROFILE_TARGET,
    HERO_FARMING_PROFILE_KEY,
    HERO_FARMING_PROFILE_TARGET,
    PROFILE_SPECS,
    Slice21DiagnosticReport,
    attach_causal_group_mean,
    attach_hero_profile_observations,
    classify_slice21,
    run_hero_performance_profile_diagnostics,
    slice21_report_to_jsonable,
)
from dota_predictor.training.hero_position_meta_state import (
    CLASSIFICATION_A as SLICE24_CLASSIFICATION_A,
)
from dota_predictor.training.hero_position_meta_state import (
    CLASSIFICATION_B as SLICE24_CLASSIFICATION_B,
)
from dota_predictor.training.hero_position_meta_state import (
    CLASSIFICATION_C as SLICE24_CLASSIFICATION_C,
)
from dota_predictor.training.hero_position_meta_state import (
    ELO_RESIDUAL_COLUMN,
    RECENT_WINDOW_DAYS_ALT,
    RECENT_WINDOW_DAYS_PRIMARY,
    SLICE24_DIAGNOSTIC_COLUMNS,
    SLICE24_DIAGNOSTIC_ONLY,
    SLICE24_FROZEN_COMPONENTS,
    SLICE24_RESEARCH_CLASSIFICATION,
    SLICE24_RESIDUAL_SHRINKAGE_K_FROZEN,
    SLICE24_STATE_COLUMNS,
    WINDOW_SPECS,
    Slice24DiagnosticReport,
    attach_elo_residual,
    attach_hero_position_meta_state,
    causal_previous_version_id,
    classify_slice24,
    run_hero_position_meta_diagnostics,
    slice24_report_to_jsonable,
)
from dota_predictor.training.player_hero_pool_state import (
    CLASSIFICATION_A as SLICE25_CLASSIFICATION_A,
)
from dota_predictor.training.player_hero_pool_state import (
    CLASSIFICATION_B as SLICE25_CLASSIFICATION_B,
)
from dota_predictor.training.player_hero_pool_state import (
    CLASSIFICATION_C as SLICE25_CLASSIFICATION_C,
)
from dota_predictor.training.player_hero_pool_state import (
    HIERARCHICAL_K_GRID,
    POOL_WINDOW_SPECS,
    SCORING_MIXTURE_EPSILON,
    SLICE25_BOOTSTRAP_RESAMPLES,
    SLICE25_BOOTSTRAP_SEED,
    SLICE25_DIAGNOSTIC_ONLY,
    SLICE25_FROZEN_COMPONENTS,
    SLICE25_RESEARCH_CLASSIFICATION,
    SLICE25_STATE_COLUMNS,
    Slice25DiagnosticReport,
    attach_player_hero_pool_state,
    classify_slice25,
    effective_pool_size,
    pool_entropy,
    run_player_hero_pool_diagnostics,
    score_distribution,
    scoring_candidates,
    select_hierarchical_k,
    slice25_report_to_jsonable,
)
from dota_predictor.training.sequential_draft_state import (
    CLASSIFICATION_A as SLICE26_CLASSIFICATION_A,
)
from dota_predictor.training.sequential_draft_state import (
    CLASSIFICATION_B as SLICE26_CLASSIFICATION_B,
)
from dota_predictor.training.sequential_draft_state import (
    CLASSIFICATION_C as SLICE26_CLASSIFICATION_C,
)
from dota_predictor.training.sequential_draft_state import (
    BOUNDARY_CONVENTION,
    SLICE26_DIAGNOSTIC_ONLY,
    SLICE26_FROZEN_COMPONENTS,
    SLICE26_RESEARCH_CLASSIFICATION,
    SLICE26_STATE_KEYS,
    Slice26DiagnosticReport,
    audit_draft_events_population,
    build_draft_prefix_state,
    build_sequential_draft_states,
    classify_match_draft_category,
    classify_slice26,
    compare_terminal_picks_to_players,
    event_is_actual,
    reconstruct_events_from_prefix,
    run_sequential_draft_state_diagnostics,
    slice26_report_to_jsonable,
)
from dota_predictor.training.sequential_draft_benchmark import (
    CLASSIFICATION_A as SLICE27_CLASSIFICATION_A,
)
from dota_predictor.training.sequential_draft_benchmark import (
    CLASSIFICATION_B as SLICE27_CLASSIFICATION_B,
)
from dota_predictor.training.sequential_draft_benchmark import (
    CLASSIFICATION_C as SLICE27_CLASSIFICATION_C,
)
from dota_predictor.training.sequential_draft_benchmark import (
    CHECKPOINTS,
    HOLDOUT_POLICY as SLICE27_HOLDOUT_POLICY,
    SLICE27_BOOTSTRAP_RESAMPLES,
    SLICE27_BOOTSTRAP_SEED,
    SLICE27_CANDIDATE_SPEC_NAME,
    SLICE27_DIAGNOSTIC_ONLY,
    SLICE27_FROZEN_COMPONENTS,
    SLICE27_PICKS_PLUS_BANS_SPEC_NAME,
    SLICE27_REFERENCE_SPEC_NAME,
    SLICE27_RESEARCH_CLASSIFICATION,
    Slice27BenchmarkReport,
    boundary_after_n_successful_picks,
    classify_slice27,
    encode_side_aware_indicators,
    run_slice27_sequential_draft_benchmark,
    slice27_report_to_jsonable,
)
from dota_predictor.training.next_pick_policy import (
    CLASSIFICATION_A as SLICE28_CLASSIFICATION_A,
)
from dota_predictor.training.next_pick_policy import (
    CLASSIFICATION_B as SLICE28_CLASSIFICATION_B,
)
from dota_predictor.training.next_pick_policy import (
    CLASSIFICATION_C as SLICE28_CLASSIFICATION_C,
)
from dota_predictor.training.next_pick_policy import (
    HOLDOUT_POLICY as SLICE28_HOLDOUT_POLICY,
    SLICE28_BOOTSTRAP_RESAMPLES,
    SLICE28_BOOTSTRAP_SEED,
    SLICE28_DIAGNOSTIC_ONLY,
    SLICE28_FROZEN_COMPONENTS,
    SLICE28_RESEARCH_CLASSIFICATION,
    Slice28BenchmarkReport,
    build_next_pick_decision_rows,
    build_policy_feature_vector,
    candidate_universe_for_row,
    classify_slice28,
    run_slice28_next_pick_policy_benchmark,
    score_policy_distribution,
    slice28_report_to_jsonable,
    unavailable_heroes,
)
from dota_predictor.training.data_scale_diagnostics import (
    SLICE29_DIAGNOSTIC_ONLY,
    Slice29Report,
    run_slice29_data_scale_benchmark,
    slice29_report_to_jsonable,
)
from dota_predictor.training.hero_requirement_state import (
    CLASSIFICATION_A as SLICE22_CLASSIFICATION_A,
)
from dota_predictor.training.hero_requirement_state import (
    CLASSIFICATION_B as SLICE22_CLASSIFICATION_B,
)
from dota_predictor.training.hero_requirement_state import (
    CLASSIFICATION_C as SLICE22_CLASSIFICATION_C,
)
from dota_predictor.training.hero_requirement_state import (
    FROZEN_HERO_COMBAT_SHRINKAGE_K,
    FROZEN_HERO_FARM_SHRINKAGE_K,
    HERO_COMBAT_SHRINKAGE_GRID,
    HERO_FARM_SHRINKAGE_GRID,
    PREFERRED_TUNE_END,
    SLICE22_STATE_COLUMNS,
    Slice22DiagnosticReport,
    attach_hero_requirement_state,
    classify_slice22,
    run_hero_requirement_state_diagnostics,
    slice22_report_to_jsonable,
)
from dota_predictor.training.logistic_model import (
    LogisticRegressionConfig,
    LogisticRegressionPredictor,
    build_logistic_pipeline,
    standardized_coefficients,
)
from dota_predictor.training.memory_policy import (
    MEMORY_POLICIES,
    POLICY_CURRENT_PLUS_PREVIOUS_VERSION,
    POLICY_EXPANDING,
    POLICY_LAST_180D,
    POLICY_LAST_365D,
    MemoryRestrictedFold,
    restrict_fold_to_memory,
)
from dota_predictor.training.metrics import EvaluationMetrics, evaluate_probabilities
from dota_predictor.training.patch_maturity_diagnostics import (
    DRAFT_BLOCK_SPEC_NAMES,
    PatchMaturityDiagnosticReport,
    attach_patch_maturity,
    build_familiarity_mix,
    run_patch_maturity_diagnostics,
)
from dota_predictor.training.player_combat_benchmark import (
    SLICE20_CANDIDATE_SPEC,
    SLICE20_CANDIDATE_SPEC_NAME,
    SLICE20_FROZEN_SPECS,
    SLICE20_REFERENCE_SPEC,
    SLICE20_REFERENCE_SPEC_NAME,
    Slice20Assembly,
    Slice20BenchmarkReport,
    build_slice20_model_ready_dataset,
    classify_slice20,
    run_slice20_player_combat_benchmark,
    slice20_report_to_jsonable,
)
from dota_predictor.training.player_combat_comparison import (
    Slice19DiagnosticReport,
    build_player_combat_comparison,
    build_player_combat_state,
    run_player_combat_comparison_diagnostics,
    slice19_report_to_jsonable,
)
from dota_predictor.training.player_combat_state import (
    CAUSAL_C_COLUMN,
    COMBAT_SHRINKAGE_GRID,
    FROZEN_COMBAT_SHRINKAGE_K,
    SLICE18_STATE_COLUMNS,
    Slice18DiagnosticReport,
    attach_causal_candidate_c,
    attach_player_combat_state,
    classify_slice18,
    run_player_combat_state_diagnostics,
    slice18_report_to_jsonable,
)
from dota_predictor.training.player_farming_benchmark import (
    CLASSIFICATION_A,
    CLASSIFICATION_B,
    CLASSIFICATION_C,
    HOLDOUT_POLICY,
    SLICE16_CANDIDATE_SPEC,
    SLICE16_CANDIDATE_SPEC_NAME,
    SLICE16_FROZEN_SPECS,
    SLICE16_REFERENCE_SPEC,
    SLICE16_REFERENCE_SPEC_NAME,
    Slice16Assembly,
    Slice16BenchmarkReport,
    build_slice16_model_ready_dataset,
    classify_slice16,
    run_slice16_player_farming_benchmark,
    slice16_report_to_jsonable,
)
from dota_predictor.training.player_farming_comparison import (
    Slice15DiagnosticReport,
    build_player_farming_comparison,
    build_player_farming_state,
    run_player_farming_comparison_diagnostics,
    slice15_report_to_jsonable,
)
from dota_predictor.training.player_farming_state import (
    CAUSAL_B_COLUMN,
    FROZEN_CANDIDATE_B,
    FROZEN_SHRINKAGE_K,
    SHRINKAGE_GRID,
    Slice14DiagnosticReport,
    attach_causal_candidate_b,
    attach_player_farming_state,
    run_player_farming_state_diagnostics,
    slice14_report_to_jsonable,
)
from dota_predictor.training.player_hero_compatibility import (
    CLASSIFICATION_A as SLICE23_CLASSIFICATION_A,
)
from dota_predictor.training.player_hero_compatibility import (
    CLASSIFICATION_B as SLICE23_CLASSIFICATION_B,
)
from dota_predictor.training.player_hero_compatibility import (
    CLASSIFICATION_C as SLICE23_CLASSIFICATION_C,
)
from dota_predictor.training.player_hero_compatibility import (
    COMBAT_SPEC,
    COMPATIBILITY_TERM_NAMES,
    FARMING_SPEC,
    MODEL_SPECS,
    SLICE23_DIAGNOSTIC_COLUMNS,
    SLICE23_DIAGNOSTIC_ONLY,
    SLICE23_FIT_SCORE_FROZEN,
    SLICE23_RESEARCH_CLASSIFICATION,
    Slice23DiagnosticReport,
    attach_compatibility_terms,
    attach_player_hero_compatibility_terms,
    classify_slice23,
    compatibility_terms,
    eligibility_mask,
    permute_hero_requirement,
    run_compatibility_diagnostics_on_frame,
    run_player_hero_compatibility_diagnostics,
    slice23_report_to_jsonable,
)
from dota_predictor.training.player_hero_elo_diagnostics import (
    MIN_GAMES_FOR_K_ESTIMATE,
    ShrinkageKEstimate,
    Slice10DiagnosticReport,
    appearance_residuals,
    estimate_shrinkage_k,
    run_player_hero_elo_diagnostics,
    slice10_report_to_jsonable,
)
from dota_predictor.training.player_performance_target import (
    CANDIDATE_COLUMN_NAMES,
    CANDIDATE_SPECS,
    Slice12DiagnosticReport,
    attach_candidate_targets,
    build_player_performance_frame,
    candidate_position_means_table,
    restrict_development,
    run_player_performance_target_diagnostics,
    slice12_report_to_jsonable,
)
from dota_predictor.training.post_draft import (
    PostDraftBenchmarkReport,
    PostDraftBlockAblationReport,
    build_post_draft_model_ready_dataset,
    run_post_draft_benchmark,
    run_post_draft_block_ablation,
)
from dota_predictor.training.preprocessing import (
    PreprocessingSpec,
    build_preprocessing_pipeline,
)
from dota_predictor.training.slice7_meta_player_hero import (
    CAREER_SAMPLE_BUCKET_ORDER,
    COMPATIBILITY_BUCKET_ORDER,
    CONTEST_SHIFT_ABS_DELTA,
    LOW_N_VERSION_THRESHOLD,
    MIN_EXPLICIT_FOR_ROLE_SHIFT,
    PATCH_MATURITY_BIN_ORDER,
    SLICE7_COMBINED_SPEC_NAME,
    SLICE7_RECENT20_SPEC_NAME,
    SLICE7_RECENT20_VOLUME_SPEC_NAME,
    SLICE7_ROLE_SPEC_NAME,
    SLICE7_SAME_VERSION_SPEC_NAME,
    SLICE7_SAME_VERSION_VOLUME_SPEC_NAME,
    Slice7Assembly,
    Slice7BenchmarkReport,
    assign_career_sample_bucket,
    assign_compatibility_bucket,
    assign_patch_maturity_bin,
    build_slice7_model_ready_dataset,
    describe_hero_shift_groups,
    run_slice7_meta_player_hero_benchmark,
)
from dota_predictor.training.slice8_player_hero_gating import (
    COMPATIBILITY_BIN_ORDER,
    CROSS_CELL_ORDER,
    EVIDENCE_BIN_ORDER,
    GATE_CANDIDATE_ORDER,
    SLICE8_EVIDENCE_SPEC_NAME,
    SLICE8_FULL_SPEC_NAME,
    SLICE8_PATCH_SPEC_NAME,
    SLICE8_ROLE_SPEC_NAME,
    CareerGateCandidate,
    GateKind,
    Slice8Assembly,
    Slice8BenchmarkReport,
    add_slice8_interaction_columns,
    apply_career_gate,
    assert_slice7_slice8_identity,
    assign_train_tertile_bin,
    build_slice8_context_frame,
    build_slice8_model_ready_dataset,
    career_gate_weights,
    gates_from_train,
    run_slice8_player_hero_gating_benchmark,
    select_career_gate,
    train_tertile_edges,
)
from dota_predictor.training.slice9_frozen_holdout import (
    FROZEN_DEVELOPMENT_END,
    FROZEN_DEVELOPMENT_MATCH_COUNT,
    FROZEN_DEVELOPMENT_OOS_MATCH_COUNT,
    FROZEN_HOLDOUT_EXPECTED_LEAGUE_ID,
    FROZEN_HOLDOUT_EXPECTED_N,
    FROZEN_PREPROCESSING_SPEC,
    FrozenHoldoutAlreadyEvaluatedError,
    FrozenHoldoutEmptyError,
    FrozenHoldoutEvaluation,
    FrozenHoldoutProtocol,
    FrozenHoldoutSplit,
    HoldoutInventory,
    assert_development_frame_excludes_holdout,
    assert_frozen_holdout_ready,
    chronology_bins,
    development_end_from_slice8_frame,
    evaluate_frozen_holdout,
    holdout_mask,
    inventory_holdout,
    load_frozen_holdout_eval_dir,
    load_frozen_holdout_evaluation,
    record_frozen_holdout_protocol,
    resolve_frozen_holdout_split,
    subset_model_ready_dataset,
    utc_datetime,
)
from dota_predictor.training.split import (
    DEFAULT_SPLIT_CONFIG,
    ChronologicalSplit,
    ChronologicalSplitConfig,
    ChronologicalSplitError,
    DatasetPartition,
    SplitBoundaries,
    chronological_split,
    resolve_split_boundaries,
)
from dota_predictor.training.walk_forward import (
    DEFAULT_WALK_FORWARD_CONFIG,
    ELO_BLOCK_SPEC_NAME,
    WalkForwardConfig,
    WalkForwardFold,
    WalkForwardReport,
    resolve_walk_forward_folds,
    run_post_draft_walk_forward,
)
from dota_predictor.training.walk_forward_memory import (
    WalkForwardMemoryReport,
    run_walk_forward_memory_diagnostics,
)

__all__ = [
    "ALL_FEATURE_COLUMNS",
    "CANDIDATE_COLUMN_NAMES",
    "CANDIDATE_SPECS",
    "CAREER_SAMPLE_BUCKET_ORDER",
    "CAUSAL_B_COLUMN",
    "CAUSAL_C_COLUMN",
    "CLASSIFICATION_A",
    "CLASSIFICATION_B",
    "CLASSIFICATION_C",
    "COMBAT_CANDIDATE_COLUMN_NAMES",
    "COMBAT_CANDIDATE_SPECS",
    "COMBAT_SHRINKAGE_GRID",
    "COMBAT_SPEC",
    "COMPATIBILITY_BIN_ORDER",
    "COMPATIBILITY_BUCKET_ORDER",
    "COMPATIBILITY_TERM_NAMES",
    "CONTEST_SHIFT_ABS_DELTA",
    "CROSS_CELL_ORDER",
    "DEFAULT_SPLIT_CONFIG",
    "DEFAULT_WALK_FORWARD_CONFIG",
    "DRAFT_BLOCK_SPEC_NAMES",
    "DRAFT_COMPARISON_FEATURE_COLUMNS",
    "ELO_BLOCK_SPEC_NAME",
    "ELO_ONLY_FEATURE_COLUMNS",
    "ELO_PLUS_ALL_THREE_COLUMNS",
    "ELO_PLUS_DRAFT_COMPARISON_COLUMNS",
    "ELO_PLUS_HERO_META_COLUMNS",
    "ELO_PLUS_PLAYER_AND_TEAM_HERO_COLUMNS",
    "ELO_PLUS_PLAYER_COMBAT_COLUMNS",
    "ELO_PLUS_PLAYER_FARMING_COLUMNS",
    "ELO_PLUS_PLAYER_HERO_COLUMNS",
    "ELO_PLUS_TEAM_HERO_COLUMNS",
    "ELO_RESIDUAL_COLUMN",
    "EVIDENCE_BIN_ORDER",
    "FARMING_CANDIDATE_COLUMN_NAMES",
    "FARMING_CANDIDATE_SPECS",
    "FARMING_SPEC",
    "FROZEN_CANDIDATE_B",
    "FROZEN_COMBAT_CANDIDATE",
    "FROZEN_COMBAT_SHRINKAGE_K",
    "FROZEN_DEVELOPMENT_END",
    "FROZEN_DEVELOPMENT_MATCH_COUNT",
    "FROZEN_DEVELOPMENT_OOS_MATCH_COUNT",
    "FROZEN_HERO_COMBAT_SHRINKAGE_K",
    "FROZEN_HERO_FARM_SHRINKAGE_K",
    "FROZEN_HOLDOUT_EXPECTED_LEAGUE_ID",
    "FROZEN_HOLDOUT_EXPECTED_N",
    "FROZEN_PREPROCESSING_SPEC",
    "FROZEN_SHRINKAGE_K",
    "GATE_CANDIDATE_ORDER",
    "HERO_COMBAT_PROFILE_KEY",
    "HERO_COMBAT_PROFILE_TARGET",
    "HERO_COMBAT_SHRINKAGE_GRID",
    "HERO_FARMING_PROFILE_KEY",
    "HERO_FARMING_PROFILE_TARGET",
    "HERO_FARM_SHRINKAGE_GRID",
    "HIERARCHICAL_K_GRID",
    "HERO_META_COMPARISON_COLUMNS",
    "HISTORICAL_WITHOUT_ELO_COLUMNS",
    "HOLDOUT_POLICY",
    "LOW_N_VERSION_THRESHOLD",
    "MEMORY_POLICIES",
    "MIN_EXPLICIT_FOR_ROLE_SHIFT",
    "MIN_GAMES_FOR_K_ESTIMATE",
    "MODEL_SPECS",
    "PATCH_MATURITY_BIN_ORDER",
    "PLAYER_COMBAT_COMPARISON_COLUMNS",
    "PLAYER_COMBAT_FEATURE_COLUMNS",
    "PLAYER_FARMING_COMPARISON_COLUMNS",
    "PLAYER_FARMING_FEATURE_COLUMNS",
    "PLAYER_HERO_COMPARISON_COLUMNS",
    "POLICY_CURRENT_PLUS_PREVIOUS_VERSION",
    "POLICY_EXPANDING",
    "POLICY_LAST_180D",
    "POLICY_LAST_365D",
    "POOL_WINDOW_SPECS",
    "POST_DRAFT_BLOCK_ABLATION_SPECS",
    "PREFERRED_TUNE_END",
    "PROFILE_SPECS",
    "RECENT_WINDOW_DAYS_ALT",
    "RECENT_WINDOW_DAYS_PRIMARY",
    "SCORING_MIXTURE_EPSILON",
    "SHRINKAGE_GRID",
    "SLICE7_CAREER_SPEC_NAME",
    "SLICE7_COMBINED_SPEC_NAME",
    "SLICE7_META_PLAYER_HERO_SPECS",
    "SLICE7_RECENT20_SPEC_NAME",
    "SLICE7_RECENT20_VOLUME_SPEC_NAME",
    "SLICE7_ROLE_SPEC_NAME",
    "SLICE7_SAME_VERSION_SPEC_NAME",
    "SLICE7_SAME_VERSION_VOLUME_SPEC_NAME",
    "SLICE8_CAREER_SPEC_NAME",
    "SLICE8_EVIDENCE_SPEC_NAME",
    "SLICE8_FULL_SPEC_NAME",
    "SLICE8_GATE_SPEC_NAME",
    "SLICE8_INTERACTION_COLUMNS",
    "SLICE8_META_PLAYER_HERO_SPECS",
    "SLICE8_PATCH_SPEC_NAME",
    "SLICE8_ROLE_SPEC_NAME",
    "SLICE8_STATIC_SPECS",
    "SLICE9_CANDIDATE_SPEC",
    "SLICE9_CANDIDATE_SPEC_NAME",
    "SLICE9_FROZEN_SPECS",
    "SLICE9_REFERENCE_SPEC",
    "SLICE9_REFERENCE_SPEC_NAME",
    "SLICE15_CANDIDATE_SPEC",
    "SLICE15_CANDIDATE_SPEC_NAME",
    "SLICE15_FROZEN_SPECS",
    "SLICE15_REFERENCE_SPEC",
    "SLICE15_REFERENCE_SPEC_NAME",
    "SLICE16_CANDIDATE_SPEC",
    "SLICE16_CANDIDATE_SPEC_NAME",
    "SLICE16_FROZEN_SPECS",
    "SLICE16_REFERENCE_SPEC",
    "SLICE16_REFERENCE_SPEC_NAME",
    "SLICE18_STATE_COLUMNS",
    "SLICE19_CANDIDATE_SPEC",
    "SLICE19_CANDIDATE_SPEC_NAME",
    "SLICE19_FROZEN_SPECS",
    "SLICE19_REFERENCE_SPEC",
    "SLICE19_REFERENCE_SPEC_NAME",
    "SLICE20_CANDIDATE_SPEC",
    "SLICE20_CANDIDATE_SPEC_NAME",
    "SLICE20_FROZEN_SPECS",
    "SLICE20_REFERENCE_SPEC",
    "SLICE20_REFERENCE_SPEC_NAME",
    "SLICE21_CLASSIFICATION_A",
    "SLICE21_CLASSIFICATION_B",
    "SLICE21_CLASSIFICATION_C",
    "SLICE22_CLASSIFICATION_A",
    "SLICE22_CLASSIFICATION_B",
    "SLICE22_CLASSIFICATION_C",
    "SLICE22_STATE_COLUMNS",
    "SLICE23_CLASSIFICATION_A",
    "SLICE23_CLASSIFICATION_B",
    "SLICE23_CLASSIFICATION_C",
    "SLICE23_DIAGNOSTIC_COLUMNS",
    "SLICE23_DIAGNOSTIC_ONLY",
    "SLICE23_FIT_SCORE_FROZEN",
    "SLICE23_RESEARCH_CLASSIFICATION",
    "SLICE24_CLASSIFICATION_A",
    "SLICE24_CLASSIFICATION_B",
    "SLICE24_CLASSIFICATION_C",
    "SLICE24_DIAGNOSTIC_COLUMNS",
    "SLICE24_DIAGNOSTIC_ONLY",
    "SLICE24_FROZEN_COMPONENTS",
    "SLICE24_RESEARCH_CLASSIFICATION",
    "SLICE24_RESIDUAL_SHRINKAGE_K_FROZEN",
    "SLICE24_STATE_COLUMNS",
    "SLICE25_CLASSIFICATION_A",
    "SLICE25_CLASSIFICATION_B",
    "SLICE25_CLASSIFICATION_C",
    "SLICE25_BOOTSTRAP_RESAMPLES",
    "SLICE25_BOOTSTRAP_SEED",
    "SLICE25_DIAGNOSTIC_ONLY",
    "SLICE25_FROZEN_COMPONENTS",
    "SLICE25_RESEARCH_CLASSIFICATION",
    "SLICE25_STATE_COLUMNS",
    "BOUNDARY_CONVENTION",
    "SLICE26_CLASSIFICATION_A",
    "SLICE26_CLASSIFICATION_B",
    "SLICE26_CLASSIFICATION_C",
    "SLICE26_DIAGNOSTIC_ONLY",
    "SLICE26_FROZEN_COMPONENTS",
    "SLICE26_RESEARCH_CLASSIFICATION",
    "SLICE26_STATE_KEYS",
    "CHECKPOINTS",
    "SLICE27_BOOTSTRAP_RESAMPLES",
    "SLICE27_BOOTSTRAP_SEED",
    "SLICE27_CANDIDATE_SPEC_NAME",
    "SLICE27_CLASSIFICATION_A",
    "SLICE27_CLASSIFICATION_B",
    "SLICE27_CLASSIFICATION_C",
    "SLICE27_DIAGNOSTIC_ONLY",
    "SLICE27_FROZEN_COMPONENTS",
    "SLICE27_HOLDOUT_POLICY",
    "SLICE27_PICKS_PLUS_BANS_SPEC_NAME",
    "SLICE27_REFERENCE_SPEC_NAME",
    "SLICE27_RESEARCH_CLASSIFICATION",
    "SLICE28_BOOTSTRAP_RESAMPLES",
    "SLICE28_BOOTSTRAP_SEED",
    "SLICE28_CLASSIFICATION_A",
    "SLICE28_CLASSIFICATION_B",
    "SLICE28_CLASSIFICATION_C",
    "SLICE28_DIAGNOSTIC_ONLY",
    "SLICE28_FROZEN_COMPONENTS",
    "SLICE28_HOLDOUT_POLICY",
    "SLICE28_RESEARCH_CLASSIFICATION",
    "Slice27BenchmarkReport",
    "Slice28BenchmarkReport",
    "Slice26DiagnosticReport",
    "TEAM_HERO_COMPARISON_COLUMNS",
    "WINDOW_SPECS",
    "BenchmarkReport",
    "BlockAblationSpec",
    "CareerGateCandidate",
    "ChronologicalSplit",
    "ChronologicalSplitConfig",
    "ChronologicalSplitError",
    "ConstantProbabilityBaseline",
    "DatasetPartition",
    "EloOnlyProbabilityBaseline",
    "EmpiricalRateBaseline",
    "EvaluationMetrics",
    "FrozenHoldoutAlreadyEvaluatedError",
    "FrozenHoldoutEmptyError",
    "FrozenHoldoutEvaluation",
    "FrozenHoldoutProtocol",
    "FrozenHoldoutSplit",
    "GateKind",
    "HoldoutInventory",
    "LogisticRegressionConfig",
    "LogisticRegressionPredictor",
    "MemoryRestrictedFold",
    "ModelReadyDataset",
    "PatchMaturityDiagnosticReport",
    "PostDraftBenchmarkReport",
    "PostDraftBlockAblationReport",
    "PreprocessingSpec",
    "ShrinkageKEstimate",
    "Slice7Assembly",
    "Slice7BenchmarkReport",
    "Slice8Assembly",
    "Slice8BenchmarkReport",
    "Slice10DiagnosticReport",
    "Slice12DiagnosticReport",
    "Slice13DiagnosticReport",
    "Slice14DiagnosticReport",
    "Slice15DiagnosticReport",
    "Slice16Assembly",
    "Slice16BenchmarkReport",
    "Slice17DiagnosticReport",
    "Slice18DiagnosticReport",
    "Slice19DiagnosticReport",
    "Slice20Assembly",
    "Slice20BenchmarkReport",
    "Slice21DiagnosticReport",
    "Slice22DiagnosticReport",
    "Slice23DiagnosticReport",
    "Slice24DiagnosticReport",
    "Slice25DiagnosticReport",
    "Slice26DiagnosticReport",
    "SplitBoundaries",
    "TrainingDatasetError",
    "WalkForwardConfig",
    "WalkForwardFold",
    "WalkForwardMemoryReport",
    "WalkForwardReport",
    "add_slice8_interaction_columns",
    "appearance_residuals",
    "apply_career_gate",
    "assert_development_frame_excludes_holdout",
    "assert_frozen_holdout_ready",
    "assert_slice7_slice8_identity",
    "assign_career_sample_bucket",
    "assign_compatibility_bucket",
    "assign_patch_maturity_bin",
    "assign_train_tertile_bin",
    "attach_candidate_targets",
    "attach_causal_candidate_b",
    "attach_causal_candidate_c",
    "attach_causal_group_mean",
    "attach_combat_candidates",
    "attach_compatibility_terms",
    "attach_elo_residual",
    "attach_farming_candidates",
    "attach_hero_position_meta_state",
    "attach_hero_profile_observations",
    "attach_hero_requirement_state",
    "attach_patch_maturity",
    "attach_player_combat_state",
    "attach_player_farming_state",
    "attach_player_hero_compatibility_terms",
    "attach_player_hero_pool_state",
    "audit_draft_events_population",
    "build_draft_prefix_state",
    "build_next_pick_decision_rows",
    "build_policy_feature_vector",
    "build_sequential_draft_states",
    "build_familiarity_mix",
    "build_logistic_pipeline",
    "build_model_ready_dataset",
    "build_player_combat_comparison",
    "build_player_combat_state",
    "build_player_farming_comparison",
    "build_player_farming_state",
    "build_player_performance_frame",
    "build_post_draft_model_ready_dataset",
    "build_preprocessing_pipeline",
    "build_slice7_model_ready_dataset",
    "build_slice8_context_frame",
    "build_slice8_model_ready_dataset",
    "build_slice16_model_ready_dataset",
    "build_slice20_model_ready_dataset",
    "candidate_position_means_table",
    "candidate_universe_for_row",
    "career_gate_weights",
    "causal_previous_version_id",
    "chronological_split",
    "chronology_bins",
    "classify_slice16",
    "classify_slice17",
    "classify_slice18",
    "classify_slice20",
    "classify_slice21",
    "classify_slice22",
    "classify_slice23",
    "classify_slice24",
    "classify_slice25",
    "classify_slice26",
    "classify_slice27",
    "classify_slice28",
    "classify_match_draft_category",
    "compare_terminal_picks_to_players",
    "boundary_after_n_successful_picks",
    "encode_side_aware_indicators",
    "event_is_actual",
    "compatibility_terms",
    "describe_hero_shift_groups",
    "development_end_from_slice8_frame",
    "effective_pool_size",
    "eligibility_mask",
    "estimate_shrinkage_k",
    "evaluate_frozen_holdout",
    "evaluate_probabilities",
    "gates_from_train",
    "holdout_mask",
    "inventory_holdout",
    "load_frozen_holdout_eval_dir",
    "load_frozen_holdout_evaluation",
    "missing_value_report",
    "permute_hero_requirement",
    "pool_entropy",
    "record_frozen_holdout_protocol",
    "resolve_frozen_holdout_split",
    "resolve_split_boundaries",
    "resolve_walk_forward_folds",
    "restrict_development",
    "restrict_fold_to_memory",
    "rows_with_any_missing",
    "score_distribution",
    "score_policy_distribution",
    "scoring_candidates",
    "run_combat_performance_target_diagnostics",
    "run_compatibility_diagnostics_on_frame",
    "run_farming_performance_target_diagnostics",
    "run_hero_performance_profile_diagnostics",
    "run_hero_position_meta_diagnostics",
    "run_hero_requirement_state_diagnostics",
    "run_patch_maturity_diagnostics",
    "run_player_combat_comparison_diagnostics",
    "run_player_combat_state_diagnostics",
    "run_player_farming_comparison_diagnostics",
    "run_player_farming_state_diagnostics",
    "run_player_hero_compatibility_diagnostics",
    "run_player_hero_elo_diagnostics",
    "run_player_hero_pool_diagnostics",
    "run_sequential_draft_state_diagnostics",
    "run_slice27_sequential_draft_benchmark",
    "run_slice28_next_pick_policy_benchmark",
    "run_slice29_data_scale_benchmark",
    "slice29_report_to_jsonable",
    "SLICE29_DIAGNOSTIC_ONLY",
    "Slice29Report",
    "reconstruct_events_from_prefix",
    "run_player_performance_target_diagnostics",
    "run_post_draft_benchmark",
    "run_post_draft_block_ablation",
    "run_post_draft_walk_forward",
    "run_slice7_meta_player_hero_benchmark",
    "run_slice8_player_hero_gating_benchmark",
    "run_slice16_player_farming_benchmark",
    "run_slice20_player_combat_benchmark",
    "run_step4b_benchmark",
    "run_walk_forward_memory_diagnostics",
    "select_career_gate",
    "select_hierarchical_k",
    "slice8_interaction_column",
    "slice10_report_to_jsonable",
    "slice12_report_to_jsonable",
    "slice13_report_to_jsonable",
    "slice14_report_to_jsonable",
    "slice15_report_to_jsonable",
    "slice16_report_to_jsonable",
    "slice17_report_to_jsonable",
    "slice18_report_to_jsonable",
    "slice19_report_to_jsonable",
    "slice20_report_to_jsonable",
    "slice21_report_to_jsonable",
    "slice22_report_to_jsonable",
    "slice23_report_to_jsonable",
    "slice24_report_to_jsonable",
    "slice25_report_to_jsonable",
    "slice26_report_to_jsonable",
    "slice27_report_to_jsonable",
    "slice28_report_to_jsonable",
    "standardized_coefficients",
    "subset_model_ready_dataset",
    "train_tertile_edges",
    "unavailable_heroes",
    "utc_datetime",
]
