"""initial schema

Revision ID: fc8432b8f4cf
Revises: 
Create Date: 2026-08-28 21:10:42.344505

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc8432b8f4cf'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('league_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('stratz_tier', sa.Text(), nullable=True),
    sa.Column('liquipedia_tier', sa.Text(), nullable=False),
    sa.Column('in_scope', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('curated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("liquipedia_tier IN ('T1', 'T2', 'MINOR', 'QUALIFIER', 'EXCLUDED')", name=op.f('ck_leagues_liquipedia_tier_valid')),
    sa.PrimaryKeyConstraint('league_id', name=op.f('pk_leagues'))
    )
    op.create_table('ingestion_leagues',
    sa.Column('league_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], name=op.f('fk_ingestion_leagues_league_id_leagues'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('league_id', name=op.f('pk_ingestion_leagues'))
    )
    op.create_table('league_ingestion_state',
    sa.Column('league_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('matches_seen_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cursor_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'IN_PROGRESS', 'COMPLETE', 'ERROR')", name=op.f('ck_league_ingestion_state_status_valid')),
    sa.CheckConstraint('error_count >= 0', name=op.f('ck_league_ingestion_state_error_count_non_negative')),
    sa.CheckConstraint('matches_seen_count >= 0', name=op.f('ck_league_ingestion_state_matches_seen_count_non_negative')),
    sa.ForeignKeyConstraint(['league_id'], ['ingestion_leagues.league_id'], name=op.f('fk_league_ingestion_state_league_id_ingestion_leagues')),
    sa.PrimaryKeyConstraint('league_id', name=op.f('pk_league_ingestion_state'))
    )
    op.create_table('match_ingestion_errors',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=True),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('raw_payload_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("stage IN ('FETCH', 'MAP', 'WRITE')", name=op.f('ck_match_ingestion_errors_stage_valid')),
    sa.ForeignKeyConstraint(['league_id'], ['ingestion_leagues.league_id'], name=op.f('fk_match_ingestion_errors_league_id_ingestion_leagues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_ingestion_errors'))
    )
    op.create_table('matches',
    sa.Column('match_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('league_name', sa.Text(), nullable=True),
    sa.Column('series_id', sa.BigInteger(), nullable=True),
    sa.Column('series_type', sa.Text(), nullable=True),
    sa.Column('game_number_in_series', sa.SmallInteger(), nullable=True),
    sa.Column('game_version_id', sa.Integer(), nullable=True),
    sa.Column('radiant_team_id', sa.BigInteger(), nullable=False),
    sa.Column('radiant_team_name', sa.Text(), nullable=True),
    sa.Column('dire_team_id', sa.BigInteger(), nullable=False),
    sa.Column('dire_team_name', sa.Text(), nullable=True),
    sa.Column('radiant_win', sa.Boolean(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('mapper_version', sa.Integer(), nullable=False),
    sa.Column('canonicalized_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('duration_seconds > 0', name=op.f('ck_matches_duration_seconds_positive')),
    sa.CheckConstraint('game_number_in_series IS NULL OR game_number_in_series >= 1', name=op.f('ck_matches_game_number_in_series_positive')),
    sa.CheckConstraint('radiant_team_id <> dire_team_id', name=op.f('ck_matches_radiant_dire_team_distinct')),
    sa.ForeignKeyConstraint(['league_id'], ['ingestion_leagues.league_id'], name=op.f('fk_matches_league_id_ingestion_leagues')),
    sa.PrimaryKeyConstraint('match_id', name=op.f('pk_matches'))
    )
    op.create_table('stratz_raw_matches',
    sa.Column('match_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['ingestion_leagues.league_id'], name=op.f('fk_stratz_raw_matches_league_id_ingestion_leagues')),
    sa.PrimaryKeyConstraint('match_id', name=op.f('pk_stratz_raw_matches'))
    )
    op.create_table('draft_events',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence', sa.SmallInteger(), nullable=False),
    sa.Column('action', sa.Enum('PICK', 'BAN', name='draft_action', native_enum=False), nullable=False),
    sa.Column('side', sa.Enum('RADIANT', 'DIRE', name='side', native_enum=False), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('was_successful', sa.Boolean(), nullable=True),
    sa.CheckConstraint('hero_id > 0', name=op.f('ck_draft_events_hero_id_positive')),
    sa.CheckConstraint('sequence >= 0', name=op.f('ck_draft_events_sequence_non_negative')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], name=op.f('fk_draft_events_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'sequence', name=op.f('pk_draft_events'))
    )
    op.create_table('match_players',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('side', sa.Enum('RADIANT', 'DIRE', name='side', native_enum=False), nullable=False),
    sa.Column('slot_in_side', sa.SmallInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('slot_in_side BETWEEN 0 AND 4', name=op.f('ck_match_players_slot_in_side_valid_range')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], name=op.f('fk_match_players_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'side', 'slot_in_side', name=op.f('pk_match_players')),
    sa.UniqueConstraint('match_id', 'player_id', name='match_players_unique_player')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_players')
    op.drop_table('draft_events')
    op.drop_table('stratz_raw_matches')
    op.drop_table('matches')
    op.drop_table('match_ingestion_errors')
    op.drop_table('league_ingestion_state')
    op.drop_table('ingestion_leagues')
    op.drop_table('leagues')
    # ### end Alembic commands ###
